version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shipping_postgres
    restart: always
    environment:
      POSTGRES_DB: shipping_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shipping_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shipping.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local